### ISSUE TITLE
MINVAL versus MAXVAL

### ISSUE THREAD

**Issue by thepeteriley** [RDStrauss/SEP_propagator#3]
Hi - 

There's a comment at the top of the code: 

"! To add/fix in future:
! Need to fix typo in CFL timestep determinnation. Should be MINVAL(L), not MAXVAL(L)!"

This seems like a trivial fix, so I'm probably missing the significance. It's only used in the CFL stuff briefly, but if MINVAL() is used instead, it doesn't seem to make a difference (at least in the plotted profiles). Is it just this line that requires the change:

 D_mumu_max = MAXVAL(D_mumu)!maximum value of D_mumu and used for CFL calculation

Thanks for making this code available! It's a lot of fun to play with :)

**Comment by RDStrauss** [comment]
Hi,

>> thanks for the corrections and comments. I'm happy someone is playing with it :-) 

>> Indeed, it was a trivial typo. The comment was more of a reminder than a serious issue. Luckily the MINVAL(L)/MAXVAL(L) doesn't influence the code as the timestep is determined by Duu. I should just fix it and remove the comment. Thanks!

Best wishes, Du Toit
